export const categoryIcons = {
  Beef: "🥩",
  Chicken: "🍗",
  Pork: "🍖",
  Lamb: "🍖",
  Seafood: "🐟",
  Vegetarian: "🥦",
  Vegan: "🌱",
  Dessert: "🍰",
  Pancakes: "🥞",
  Cookie: "🍪",
  Icecream: "🍨",
  Pasta: "🍝",
  Breakfast: "🍳",
  Side: "🍽️",
  Miscellaneous: "🍽️",
  Goat: "🐐",
  Starter: "🥗",
  Soup: "🍲",
  Sandwich: "🥪",
  Baking: "🥐",
  BBQ: "🔥",
  Alcoholic: "🍸",
  "Non alcoholic": "🥤",
};